<?php
/**
 * PATRON - Download Client Certificates as ZIP
 * 
 * Downloads all certificates for a client as a ZIP file
 * Usage: download_certificates.php?client_id=123
 */

require_once 'includes/db.php';
startSession();
requireLogin();

$clientId = (int)($_GET['client_id'] ?? 0);

if (!$clientId) {
    setFlash('error', 'Invalid client.');
    header('Location: clients.php');
    exit;
}

// Get client info
$client = dbFetchOne("SELECT id, name FROM clients WHERE id = ? AND deleted_at IS NULL", [$clientId]);
if (!$client) {
    setFlash('error', 'Client not found.');
    header('Location: clients.php');
    exit;
}

// Get all certificates for this client with files
$certificates = dbFetchAll("
    SELECT cc.id, cc.certificate_number, cc.issue_date, cc.expiry_date, cc.file_path,
           ct.name as type_name, ct.code as type_code, ct.category
    FROM client_certificates cc
    JOIN certificate_types ct ON cc.certificate_type_id = ct.id
    WHERE cc.client_id = ? 
      AND cc.deleted_at IS NULL
      AND cc.file_path IS NOT NULL
      AND cc.file_path != ''
    ORDER BY ct.category, ct.name
", [$clientId]) ?: [];

// Filter only existing files
$validCerts = [];
foreach ($certificates as $cert) {
    if (file_exists($cert['file_path'])) {
        $validCerts[] = $cert;
    }
}

if (empty($validCerts)) {
    setFlash('error', 'No certificate files found for this client.');
    header('Location: view_client.php?id=' . $clientId . '&tab=certificates');
    exit;
}

// Create ZIP file
$zipFileName = 'Certificates_' . preg_replace('/[^a-zA-Z0-9_-]/', '_', $client['name']) . '_' . date('Ymd_His') . '.zip';
$zipFilePath = sys_get_temp_dir() . '/' . $zipFileName;

$zip = new ZipArchive();
if ($zip->open($zipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
    setFlash('error', 'Failed to create ZIP file.');
    header('Location: view_client.php?id=' . $clientId . '&tab=certificates');
    exit;
}

// Add files to ZIP
$addedFiles = 0;
$fileIndex = [];

foreach ($validCerts as $cert) {
    $filePath = $cert['file_path'];
    $fileExt = pathinfo($filePath, PATHINFO_EXTENSION);
    
    // Create organized folder structure: Category/CertificateName_Number.ext
    $category = $cert['category'] ?? 'Other';
    $category = preg_replace('/[^a-zA-Z0-9_-]/', '_', $category);
    
    $baseName = $cert['type_code'] ?? preg_replace('/[^a-zA-Z0-9_-]/', '_', $cert['type_name']);
    
    // Add certificate number if available
    if ($cert['certificate_number']) {
        $baseName .= '_' . preg_replace('/[^a-zA-Z0-9_-]/', '_', $cert['certificate_number']);
    }
    
    // Handle duplicate names
    $fullName = $category . '/' . $baseName . '.' . $fileExt;
    $counter = 1;
    while (isset($fileIndex[$fullName])) {
        $fullName = $category . '/' . $baseName . '_' . $counter . '.' . $fileExt;
        $counter++;
    }
    $fileIndex[$fullName] = true;
    
    // Add file to ZIP
    if ($zip->addFile($filePath, $fullName)) {
        $addedFiles++;
    }
}

// Add index file with certificate details
$indexContent = "CERTIFICATE INDEX\n";
$indexContent .= "=================\n";
$indexContent .= "Client: " . $client['name'] . "\n";
$indexContent .= "Generated: " . date('d M Y, h:i A') . "\n";
$indexContent .= "Total Files: " . $addedFiles . "\n\n";
$indexContent .= str_repeat("-", 80) . "\n\n";

$currentCategory = '';
foreach ($validCerts as $cert) {
    $category = $cert['category'] ?? 'Other';
    if ($category !== $currentCategory) {
        $currentCategory = $category;
        $indexContent .= "\n[$category]\n" . str_repeat("-", 40) . "\n";
    }
    
    $indexContent .= sprintf("• %s\n", $cert['type_name']);
    $indexContent .= sprintf("  Number: %s\n", $cert['certificate_number'] ?? 'N/A');
    $indexContent .= sprintf("  Issue Date: %s\n", $cert['issue_date'] ? date('d M Y', strtotime($cert['issue_date'])) : 'N/A');
    $indexContent .= sprintf("  Expiry Date: %s\n", $cert['expiry_date'] ? date('d M Y', strtotime($cert['expiry_date'])) : 'No Expiry');
    $indexContent .= "\n";
}

$indexContent .= "\n" . str_repeat("=", 80) . "\n";
$indexContent .= "Generated by PATRON - Practice Management System\n";

$zip->addFromString('_INDEX.txt', $indexContent);

$zip->close();

// Check if ZIP was created successfully
if (!file_exists($zipFilePath)) {
    setFlash('error', 'Failed to create ZIP file.');
    header('Location: view_client.php?id=' . $clientId . '&tab=certificates');
    exit;
}

// Log the download
try {
    dbExecute("
        INSERT INTO activity_logs (user_id, action, entity_type, entity_id, details, created_at)
        VALUES (?, 'DOWNLOAD', 'CLIENT_CERTIFICATES', ?, ?, NOW())
    ", [
        $_SESSION['user_id'] ?? null,
        $clientId,
        json_encode(['files' => $addedFiles, 'client' => $client['name']])
    ]);
} catch (Exception $e) {
    // Activity log table might not exist, ignore
}

// Send file to browser
header('Content-Type: application/zip');
header('Content-Disposition: attachment; filename="' . $zipFileName . '"');
header('Content-Length: ' . filesize($zipFilePath));
header('Cache-Control: no-cache, must-revalidate');
header('Pragma: no-cache');

readfile($zipFilePath);

// Clean up temp file
unlink($zipFilePath);
exit;
