<?php

use Illuminate\Support\Facades\Route;

// Accounting Cluster 301 redirects — source: SEO Infra/Redirects/Accounting-Cluster-Redirects_2026-07-10.csv
// Registered early (before page routes) so they take precedence. Auto-generated; edit the source CSV + regenerate.
$accountingClusterRedirects = [
    ['/accounting-bookkeeping-services/delhi', '/accounting-services/delhi'],
    ['/accounting-bookkeeping-services/gurugram', '/accounting-services/gurugram'],
    ['/accounting-bookkeeping-services/mumbai', '/accounting-services/mumbai'],
    ['/accounting-bookkeeping-services/pune', '/accounting-services/pune'],
    ['/accounting-services-for-e-commerce-industry/delhi', '/accounting-services-for-e-commerce-industry'],
    ['/accounting-services-for-retail/delhi', '/accounting-services-for-retail'],
    ['/accounting-services-for-trading-industry/delhi', '/accounting-services-for-trading-industry'],
    ['/accounting-services-for-trading-industry/gurugram', '/accounting-services-for-trading-industry'],
    ['/accounting-services-for-trading-industry/pune', '/accounting-services-for-trading-industry'],
    ['/accounts-payable-outsourcing-services/delhi', '/accounts-payable-outsourcing-services'],
    ['/accounts-payable-outsourcing-services/gurugram', '/accounts-payable-outsourcing-services'],
    ['/accounts-payable-outsourcing-services/mumbai', '/accounts-payable-outsourcing-services'],
    ['/accounts-payable-outsourcing-services/pune', '/accounts-payable-outsourcing-services'],
    ['/accounts-receivable-outsourcing-services/delhi', '/accounts-receivable-outsourcing-services'],
    ['/accounts-receivable-outsourcing-services/gurugram', '/accounts-receivable-outsourcing-services'],
    ['/accounts-receivable-outsourcing-services/mumbai', '/accounts-receivable-outsourcing-services'],
    ['/accounts-receivable-outsourcing-services/pune', '/accounts-receivable-outsourcing-services'],
    ['/accounts-reconciliation-and-audit/delhi', '/accounts-reconciliation-and-audit'],
    ['/accounts-reconciliation-and-audit/gurugram', '/accounts-reconciliation-and-audit'],
    ['/accounts-reconciliation-and-audit/mumbai', '/accounts-reconciliation-and-audit'],
    ['/accounts-reconciliation-and-audit/pune', '/accounts-reconciliation-and-audit'],
    ['/backlog-bookkeeping-catch-up-services/delhi', '/backlog-bookkeeping-catch-up-services'],
    ['/backlog-bookkeeping-catch-up-services/gurugram', '/backlog-bookkeeping-catch-up-services'],
    ['/backlog-bookkeeping-catch-up-services/mumbai', '/backlog-bookkeeping-catch-up-services'],
    ['/backlog-bookkeeping-catch-up-services/pune', '/backlog-bookkeeping-catch-up-services'],
    ['/bank-credit-card-reconciliation-services/delhi', '/bank-credit-card-reconciliation-services'],
    ['/bank-credit-card-reconciliation-services/gurugram', '/bank-credit-card-reconciliation-services'],
    ['/bank-credit-card-reconciliation-services/mumbai', '/bank-credit-card-reconciliation-services'],
    ['/bank-credit-card-reconciliation-services/pune', '/bank-credit-card-reconciliation-services'],
    ['/chart-of-accounts-setup-services/delhi', '/chart-of-accounts-setup-services'],
    ['/chart-of-accounts-setup-services/gurugram', '/chart-of-accounts-setup-services'],
    ['/chart-of-accounts-setup-services/mumbai', '/chart-of-accounts-setup-services'],
    ['/chart-of-accounts-setup-services/pune', '/chart-of-accounts-setup-services'],
    ['/construction-and-real-estate-accounting-services/delhi', '/construction-and-real-estate-accounting-services'],
    ['/construction-and-real-estate-accounting-services/gurugram', '/construction-and-real-estate-accounting-services'],
    ['/construction-and-real-estate-accounting-services/mumbai', '/construction-and-real-estate-accounting-services'],
    ['/construction-and-real-estate-accounting-services/pune', '/construction-and-real-estate-accounting-services'],
    ['/esop-accounting-ind-as-102/delhi', '/esop-accounting-ind-as-102'],
    ['/esop-accounting-ind-as-102/gurugram', '/esop-accounting-ind-as-102'],
    ['/esop-accounting-ind-as-102/mumbai', '/esop-accounting-ind-as-102'],
    ['/esop-accounting-ind-as-102/pune', '/esop-accounting-ind-as-102'],
    ['/financial-statement-preparation-services/delhi', '/financial-statement-preparation-services'],
    ['/financial-statement-preparation-services/gurugram', '/financial-statement-preparation-services'],
    ['/financial-statement-preparation-services/mumbai', '/financial-statement-preparation-services'],
    ['/financial-statement-preparation-services/pune', '/financial-statement-preparation-services'],
    ['/healthcare-sector-accounting-services/delhi', '/healthcare-sector-accounting-services'],
    ['/healthcare-sector-accounting-services/gurugram', '/healthcare-sector-accounting-services'],
    ['/healthcare-sector-accounting-services/pune', '/healthcare-sector-accounting-services'],
    ['/hospitality-sector-accounting-services/delhi', '/hospitality-sector-accounting-services'],
    ['/hospitality-sector-accounting-services/gurugram', '/hospitality-sector-accounting-services'],
    ['/hospitality-sector-accounting-services/pune', '/hospitality-sector-accounting-services'],
    ['/inventory-accounting-costing-services/delhi', '/inventory-accounting-costing-services'],
    ['/inventory-accounting-costing-services/gurugram', '/inventory-accounting-costing-services'],
    ['/inventory-accounting-costing-services/mumbai', '/inventory-accounting-costing-services'],
    ['/inventory-accounting-costing-services/pune', '/inventory-accounting-costing-services'],
    ['/it-sector-accounting-services/delhi', '/it-sector-accounting-services'],
    ['/it-sector-accounting-services/gurugram', '/it-sector-accounting-services'],
    ['/it-sector-accounting-services/mumbai', '/it-sector-accounting-services'],
    ['/it-sector-accounting-services/pune', '/it-sector-accounting-services'],
    ['/migration-from-tally-to-odoo/delhi', '/migration-from-tally-to-odoo'],
    ['/migration-from-tally-to-odoo/gurugram', '/migration-from-tally-to-odoo'],
    ['/migration-from-tally-to-odoo/mumbai', '/migration-from-tally-to-odoo'],
    ['/migration-from-tally-to-odoo/pune', '/migration-from-tally-to-odoo'],
    ['/migration-from-tally-to-zoho/delhi', '/migration-from-tally-to-zoho'],
    ['/migration-from-tally-to-zoho/gurugram', '/migration-from-tally-to-zoho'],
    ['/migration-from-tally-to-zoho/mumbai', '/migration-from-tally-to-zoho'],
    ['/migration-from-tally-to-zoho/pune', '/migration-from-tally-to-zoho'],
    ['/mis-reporting-services/delhi', '/mis-reporting-services'],
    ['/mis-reporting-services/gurugram', '/mis-reporting-services'],
    ['/mis-reporting-services/mumbai', '/mis-reporting-services'],
    ['/mis-reporting-services/pune', '/mis-reporting-services'],
    ['/ngo-and-non-profit-accounting-services/delhi', '/ngo-and-non-profit-accounting-services'],
    ['/ngo-and-non-profit-accounting-services/pune', '/ngo-and-non-profit-accounting-services'],
    ['/odoo-accounting/delhi', '/odoo-accounting'],
    ['/odoo-accounting/gurugram', '/odoo-accounting'],
    ['/odoo-accounting/mumbai', '/odoo-accounting'],
    ['/odoo-accounting/pune', '/odoo-accounting'],
    ['/sop-drafting-and-implementation/delhi', '/sop-drafting-and-implementation'],
    ['/sop-drafting-and-implementation/gurugram', '/sop-drafting-and-implementation'],
    ['/sop-drafting-and-implementation/mumbai', '/sop-drafting-and-implementation'],
    ['/sop-drafting-and-implementation/pune', '/sop-drafting-and-implementation'],
    ['/tally-accounting/delhi', '/tally-accounting'],
    ['/tally-accounting/gurugram', '/tally-accounting'],
    ['/tally-accounting/mumbai', '/tally-accounting'],
    ['/tally-accounting/pune', '/tally-accounting'],
    ['/travel-and-logistics-accounting-services/delhi', '/travel-and-logistics-accounting-services'],
    ['/travel-and-logistics-accounting-services/gurugram', '/travel-and-logistics-accounting-services'],
    ['/travel-and-logistics-accounting-services/mumbai', '/travel-and-logistics-accounting-services'],
    ['/travel-and-logistics-accounting-services/pune', '/travel-and-logistics-accounting-services'],
    ['/xero-accounting/gurugram', '/xero-accounting'],
    ['/xero-accounting/pune', '/xero-accounting'],
    ['/year-end-closing-finalisation-services/delhi', '/year-end-closing-finalisation-services'],
    ['/year-end-closing-finalisation-services/gurugram', '/year-end-closing-finalisation-services'],
    ['/year-end-closing-finalisation-services/mumbai', '/year-end-closing-finalisation-services'],
    ['/year-end-closing-finalisation-services/pune', '/year-end-closing-finalisation-services'],
    ['/zoho-books-accounting/bangalore', '/zoho-books-accounting'],
    ['/zoho-books-accounting/chennai', '/zoho-books-accounting'],
    ['/zoho-books-accounting/delhi', '/zoho-books-accounting'],
    ['/zoho-books-accounting/gurugram', '/zoho-books-accounting'],
    ['/zoho-books-accounting/hyderabad', '/zoho-books-accounting'],
    ['/zoho-books-accounting/kolkata', '/zoho-books-accounting'],
    ['/zoho-books-accounting/mumbai', '/zoho-books-accounting'],
    ['/zoho-books-accounting/pune', '/zoho-books-accounting'],
    ['/quickbooks-accounting', '/zoho-books-accounting'],
    ['/migration-from-tally-to-quickbooks', '/migration-from-tally-to-zoho'],
    ['/migration-from-zoho-to-quickbooks', '/zoho-books-accounting'],
    ['/migration-from-quickbooks-to-zoho', '/zoho-books-accounting'],

    // QuickBooks retired entirely 2026-08-11 - every QuickBooks service line, in both
    // directions. The 4 national pages were already redirected above, but their 16 city
    // pages had been left live and in the sitemap, orphaned from parents that no longer
    // resolve. All 16 are retired here.
    // Every target below is a 200 (never itself a redirect), so no chains are introduced.
    ['/migration-from-quickbooks-to-zoho/delhi', '/zoho-books-accounting'],
    ['/migration-from-quickbooks-to-zoho/gurugram', '/zoho-books-accounting'],
    ['/migration-from-quickbooks-to-zoho/mumbai', '/zoho-books-accounting'],
    ['/migration-from-quickbooks-to-zoho/pune', '/zoho-books-accounting'],
    ['/quickbooks-accounting/delhi', '/zoho-books-accounting'],
    ['/quickbooks-accounting/gurugram', '/zoho-books-accounting'],
    ['/quickbooks-accounting/mumbai', '/zoho-books-accounting'],
    ['/quickbooks-accounting/pune', '/zoho-books-accounting'],
    ['/migration-from-zoho-to-quickbooks/delhi', '/zoho-books-accounting'],
    ['/migration-from-zoho-to-quickbooks/gurugram', '/zoho-books-accounting'],
    ['/migration-from-zoho-to-quickbooks/mumbai', '/zoho-books-accounting'],
    ['/migration-from-zoho-to-quickbooks/pune', '/zoho-books-accounting'],
    // Mumbai and Pune keep city-level relevance - live Tally-to-Zoho city pages exist for both.
    ['/migration-from-tally-to-quickbooks/mumbai', '/tally-to-zoho-migration/mumbai'],
    ['/migration-from-tally-to-quickbooks/pune', '/tally-to-zoho-migration/pune'],
    ['/migration-from-tally-to-quickbooks/delhi', '/migration-from-tally-to-zoho'],
    ['/migration-from-tally-to-quickbooks/gurugram', '/migration-from-tally-to-zoho'],
];

foreach ($accountingClusterRedirects as $__r) {
    Route::redirect($__r[0], $__r[1], 301);
}
