@extends('admin.layouts.app')

@section('title', 'Create Page Category')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-6">
    <div>
        <h1 class="h1">Create Page Category</h1>
        <p class="text-small">Add a new category for organizing your website pages</p>
    </div>
    <a href="{{ route('admin.page-categories.index') }}" class="btn-professional btn-professional-outline">
        <i class="bi bi-arrow-left"></i>Back to Categories
    </a>
</div>

<div class="card-professional">
    <div class="card-professional-header">
        <h3 class="card-professional-title">Category Information</h3>
    </div>
    <div class="card-professional-body">
        <form method="POST" action="{{ route('admin.page-categories.store') }}">
            @csrf
            
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-6); margin-bottom: var(--space-6);">
                <div class="form-professional">
                    <label for="name" class="form-label-professional">Category Name <span style="color: var(--red-alert);">*</span></label>
                    <input type="text" 
                           class="form-input-professional @error('name') is-invalid @enderror" 
                           id="name" 
                           name="name" 
                           value="{{ old('name') }}" 
                           required 
                           maxlength="255"
                           placeholder="Enter category name">
                    @error('name')
                        <div style="color: var(--red-alert); font-size: var(--text-xs); margin-top: var(--space-1);">{{ $message }}</div>
                    @enderror
                </div>
                
                <div class="form-professional">
                    <label for="slug" class="form-label-professional">Slug</label>
                    <input type="text" 
                           class="form-input-professional @error('slug') is-invalid @enderror" 
                           id="slug" 
                           name="slug" 
                           value="{{ old('slug') }}" 
                           maxlength="255"
                           placeholder="Leave empty to auto-generate">
                    <div class="text-small" style="color: var(--neutral-gray); margin-top: var(--space-1);">URL-friendly version of the name. Leave empty to auto-generate.</div>
                    @error('slug')
                        <div style="color: var(--red-alert); font-size: var(--text-xs); margin-top: var(--space-1);">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="form-professional">
                <label for="description" class="form-label-professional">Description</label>
                <textarea class="form-input-professional @error('description') is-invalid @enderror" 
                          id="description" 
                          name="description" 
                          rows="4"
                          style="resize: vertical;"
                          placeholder="Optional description for this category">{{ old('description') }}</textarea>
                @error('description')
                    <div style="color: var(--red-alert); font-size: var(--text-xs); margin-top: var(--space-1);">{{ $message }}</div>
                @enderror
            </div>

            <div style="display: flex; justify-content: flex-end; gap: var(--space-3); margin-top: var(--space-6);">
                <a href="{{ route('admin.page-categories.index') }}" class="btn-professional btn-professional-outline">Cancel</a>
                <button type="submit" class="btn-professional btn-professional-primary">
                    <i class="bi bi-check-circle"></i>Create Category
                </button>
            </div>
        </form>
    </div>
</div>
@endsection

@push('scripts')
<script>
    // Auto-generate slug from name
    document.getElementById('name').addEventListener('input', function() {
        const slugField = document.getElementById('slug');
        if (!slugField.value || slugField.dataset.autoGenerated === 'true') {
            const slug = this.value
                .toLowerCase()
                .replace(/[^a-z0-9\s-]/g, '')
                .replace(/\s+/g, '-')
                .replace(/-+/g, '-')
                .trim('-');
            slugField.value = slug;
            slugField.dataset.autoGenerated = 'true';
        }
    });

    // Mark slug as manually edited when user types in it
    document.getElementById('slug').addEventListener('input', function() {
        this.dataset.autoGenerated = 'false';
    });
</script>
@endpush